info:
  contact: {}
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: description
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: get albums list json
swagger: "2.0"
